# This file is generated by scripts/generate-homebrew-formula.sh.
# Do not edit by hand; changes are overwritten on each release.
class Aglet < Formula
  desc "Terminal personal information manager inspired by Lotus Agenda"
  homepage "https://github.com/msnodderly/aglet"
  version "0.1.0"
  license "GPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/msnodderly/aglet/releases/download/v#{version}/aglet-#{version}-macos-aarch64.tar.gz"
      sha256 "4c59b59bd4e668adaef2785e8b3a874c7e26670a6d9f60b3c986f4eafee4918f"
    end
    on_intel do
      url "https://github.com/msnodderly/aglet/releases/download/v#{version}/aglet-#{version}-macos-x86_64.tar.gz"
      sha256 "29686ef75ba52c5f6ff3a181a11fa7c24fb0f97fe6f17076a95452a89b40fc5c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/msnodderly/aglet/releases/download/v#{version}/aglet-#{version}-linux-x86_64.tar.gz"
      sha256 "402e0b770aef801405a0493138b715b9f60c09c36750d393248e069f9cfe4519"
    end
    on_arm do
      url "https://github.com/msnodderly/aglet/releases/download/v#{version}/aglet-#{version}-linux-aarch64.tar.gz"
      sha256 "f80489a53933e1ea893b704ecde728ece9a544affeec8f980adc3d164590432d"
    end
  end

  def install
    bin.install "aglet"
  end

  test do
    assert_match "aglet", shell_output("#{bin}/aglet --help")
  end
end
